tasks:
  - env: quad_insert_a0o0
    cuts_off_on_success: true
    data_subsamp_freq: 1
  - env: quad_insert_aLoL
    cuts_off_on_success: true
    data_subsamp_freq: 1
  - env: quad_insert_aMoM
    cuts_off_on_success: true
    data_subsamp_freq: 1

training:
  full_dataset_num_trajs: 200
  dataset_num_trajs: [50, 100, 200]
  deterministic_expert: false
  runs: 10

params:
  batch_size: 256
  enc_layers: 1
  dec_layers: 1
  latent_dim: 8
  n_heads: 4
  act_lr: 1.0e-4
  dropout: 0.1
  hidden_dim: 128
  dim_feedforward: 512
  activation: relu
  kl_weight: 100

options:
  max_iter: 100
  num_evals: 10
  num_rollouts_per_eval: 10
  snapshot_save_freq: 10
  print_freq: 1
  validation_eval_freq: 10
  export_data: true
