tasks:
  - env: quad_insert_a0o0
    cuts_off_on_success: true
    data_subsamp_freq: 1
  - env: quad_insert_aLoL
    cuts_off_on_success: true
    data_subsamp_freq: 1
  - env: quad_insert_aMoM
    cuts_off_on_success: true
    data_subsamp_freq: 1

training:
  full_dataset_num_trajs: 200
  dataset_num_trajs: [50, 100, 200]
  deterministic_expert: false
  runs: 10

params:
  batch_size: 512
  num_diffusion_iters: 100
  opt_learning_rate: 0.0001
  opt_weight_decay: 0.000001
  lr_warmup_steps: 500

options:
  max_iter: 50
  num_evals: 10
  num_rollouts_per_eval: 10
  snapshot_save_freq: 5
  print_freq: 1
  validation_eval_freq: 5
  export_data: true
